pub mod arith;
pub mod ast;
mod builtins;
pub mod encoding;
pub mod error;
pub mod eval;
pub mod expand;
pub mod glob;
pub mod lexer;
pub mod parser;
mod redirect;
pub(crate) mod sys;
mod test_cmd;
pub mod var;
